/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.metodoGausJordan.JFrame;

import org.apache.commons.math3.fraction.BigFraction;

/**
 *
 * @author Hector
 */
public class JframeMatriz extends javax.swing.JFrame {

    /**
     * Creates new form JframeMatriz
     */
    public JframeMatriz() {
        initComponents();
    }
    
    public static String resolverSistema(double X1, double X2, double X3, double Y1, double Y2, double Y3,
            double Z1, double Z2, double Z3, double TI1, double TI2, double TI3) {
        
        BigFraction[][] matriz = {
            {new BigFraction(X1), new BigFraction(Y1), new BigFraction(Z1), new BigFraction(TI1)},
            {new BigFraction(X2), new BigFraction(Y2), new BigFraction(Z2), new BigFraction(TI2)},
            {new BigFraction(X3), new BigFraction(Y3), new BigFraction(Z3), new BigFraction(TI3)}
        };

        // Aplica el método de Gauss-Jordan
        int filas = matriz.length;
        int columnas = matriz[0].length;

        for (int i = 0; i < filas; i++) {
            // Hace que el pivote sea 1
            BigFraction pivote = matriz[i][i];
            for (int j = 0; j < columnas; j++) {
                matriz[i][j] = matriz[i][j].divide(pivote);
            }

            // Hace que los demás elementos en la columna del pivote sean 0
            for (int k = 0; k < filas; k++) {
                if (k != i) {
                    BigFraction factor = matriz[k][i];
                    for (int j = 0; j < columnas; j++) {
                        matriz[k][j] = matriz[k][j].subtract(matriz[i][j].multiply(factor));
                    }
                }
            }
        }

        StringBuilder respuesta = new StringBuilder("X = ");
        respuesta.append(matriz[0][columnas - 1]).append("\n");

        respuesta.append("Y = ");
        respuesta.append(matriz[1][columnas - 1]).append("\n");

        respuesta.append("Z = ");
        respuesta.append(matriz[2][columnas - 1]);

        return respuesta.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        y1 = new javax.swing.JTextField();
        y2 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        z3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlBorrar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlCalcular = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(224, 224, 224));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metodo Gauss-Jordan");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 688, 38));

        x1.setBackground(new java.awt.Color(199, 199, 199));
        x1.setForeground(new java.awt.Color(0, 0, 0));
        x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x1.setBorder(null);
        jPanel9.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 110, 36, 36));

        x2.setBackground(new java.awt.Color(199, 199, 199));
        x2.setForeground(new java.awt.Color(0, 0, 0));
        x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x2.setBorder(null);
        jPanel9.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 177, 36, 37));

        x3.setBackground(new java.awt.Color(199, 199, 199));
        x3.setForeground(new java.awt.Color(0, 0, 0));
        x3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x3.setBorder(null);
        jPanel9.add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 249, 36, 36));

        y1.setBackground(new java.awt.Color(199, 199, 199));
        y1.setForeground(new java.awt.Color(0, 0, 0));
        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y1.setBorder(null);
        jPanel9.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 110, 36, 36));

        y2.setBackground(new java.awt.Color(199, 199, 199));
        y2.setForeground(new java.awt.Color(0, 0, 0));
        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y2.setBorder(null);
        jPanel9.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 177, 36, 37));

        y3.setBackground(new java.awt.Color(199, 199, 199));
        y3.setForeground(new java.awt.Color(0, 0, 0));
        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y3.setBorder(null);
        jPanel9.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 249, 36, 36));

        z1.setBackground(new java.awt.Color(199, 199, 199));
        z1.setForeground(new java.awt.Color(0, 0, 0));
        z1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z1.setBorder(null);
        jPanel9.add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 110, 36, 36));

        z2.setBackground(new java.awt.Color(199, 199, 199));
        z2.setForeground(new java.awt.Color(0, 0, 0));
        z2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z2.setBorder(null);
        jPanel9.add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 177, 36, 37));

        z3.setBackground(new java.awt.Color(199, 199, 199));
        z3.setForeground(new java.awt.Color(0, 0, 0));
        z3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z3.setBorder(null);
        jPanel9.add(z3, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 249, 36, 36));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("X");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Y");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Z");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        ti1.setBackground(new java.awt.Color(199, 199, 199));
        ti1.setForeground(new java.awt.Color(0, 0, 0));
        ti1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti1.setBorder(null);
        ti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ti1ActionPerformed(evt);
            }
        });
        jPanel9.add(ti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 36, 36));

        ti2.setBackground(new java.awt.Color(199, 199, 199));
        ti2.setForeground(new java.awt.Color(0, 0, 0));
        ti2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti2.setBorder(null);
        jPanel9.add(ti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 36, 36));

        ti3.setBackground(new java.awt.Color(199, 199, 199));
        ti3.setForeground(new java.awt.Color(0, 0, 0));
        ti3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ti3.setBorder(null);
        jPanel9.add(ti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 36, 36));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TI");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(30, 30, 30));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel9.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 20, 180));

        pnlBorrar.setBackground(new java.awt.Color(146, 146, 146));
        pnlBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBorrarMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Borrar");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlBorrarLayout = new javax.swing.GroupLayout(pnlBorrar);
        pnlBorrar.setLayout(pnlBorrarLayout);
        pnlBorrarLayout.setHorizontalGroup(
            pnlBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBorrarLayout.setVerticalGroup(
            pnlBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel9.add(pnlBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 130, 40));

        pnlCalcular.setBackground(new java.awt.Color(146, 146, 146));
        pnlCalcular.setForeground(new java.awt.Color(255, 255, 255));
        pnlCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCalcularMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Calcular");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlCalcularLayout = new javax.swing.GroupLayout(pnlCalcular);
        pnlCalcular.setLayout(pnlCalcularLayout);
        pnlCalcularLayout.setHorizontalGroup(
            pnlCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlCalcularLayout.setVerticalGroup(
            pnlCalcularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel9.add(pnlCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 130, 40));

        txaResultados.setEditable(false);
        txaResultados.setBackground(new java.awt.Color(204, 204, 204));
        txaResultados.setColumns(20);
        txaResultados.setForeground(new java.awt.Color(0, 0, 0));
        txaResultados.setRows(5);
        jScrollPane1.setViewportView(txaResultados);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCalcularMouseClicked

        double X1 = Double.parseDouble(x1.getText());
        double X2 = Double.parseDouble(x2.getText());
        double X3 = Double.parseDouble(x3.getText());

        double Y1 = Double.parseDouble(y1.getText());
        double Y2 = Double.parseDouble(y2.getText());
        double Y3 = Double.parseDouble(y3.getText());

        double Z1 = Double.parseDouble(z1.getText());
        double Z2 = Double.parseDouble(z2.getText());
        double Z3 = Double.parseDouble(z3.getText());

        double TI1 = Double.parseDouble(ti1.getText());
        double TI2 = Double.parseDouble(ti2.getText());
        double TI3 = Double.parseDouble(ti3.getText());
        
        String respuesta = resolverSistema(X1,X2, X3, Y1, Y2, Y3, Z1, Z2, Z3, TI1, TI2, TI3);

        txaResultados.setText(respuesta);
    }//GEN-LAST:event_pnlCalcularMouseClicked

    private void ti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ti1ActionPerformed

    private void pnlBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBorrarMouseClicked
        
        x1.setText("");
        x2.setText("");
        x3.setText("");
        y1.setText("");
        y2.setText("");
        y3.setText("");
        z1.setText("");
        z2.setText("");
        z3.setText("");
        ti1.setText("");
        ti2.setText("");
        ti3.setText("");
        txaResultados.setText("");
        
    }//GEN-LAST:event_pnlBorrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeMatriz().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlBorrar;
    private javax.swing.JPanel pnlCalcular;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    private javax.swing.JTextArea txaResultados;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    private javax.swing.JTextField x3;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JTextField z3;
    // End of variables declaration//GEN-END:variables
}
