/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metodocramer;

/**
 *
 * @author Hector
 */
public class JframeMatriz extends javax.swing.JFrame {

    /**
     * Creates new form JframeMatriz
     */
    public JframeMatriz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        x1 = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        x3 = new javax.swing.JTextField();
        y1 = new javax.swing.JTextField();
        y2 = new javax.swing.JTextField();
        y3 = new javax.swing.JTextField();
        z1 = new javax.swing.JTextField();
        z2 = new javax.swing.JTextField();
        z3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ti1 = new javax.swing.JTextField();
        ti2 = new javax.swing.JTextField();
        ti3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(224, 224, 224));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metodo cramer");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 688, 38));

        x1.setBackground(new java.awt.Color(199, 199, 199));
        x1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x1.setBorder(null);
        jPanel2.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 110, 36, 36));

        x2.setBackground(new java.awt.Color(199, 199, 199));
        x2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x2.setBorder(null);
        jPanel2.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 177, 36, 37));

        x3.setBackground(new java.awt.Color(199, 199, 199));
        x3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x3.setBorder(null);
        jPanel2.add(x3, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 249, 36, 36));

        y1.setBackground(new java.awt.Color(199, 199, 199));
        y1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y1.setBorder(null);
        jPanel2.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 110, 36, 36));

        y2.setBackground(new java.awt.Color(199, 199, 199));
        y2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y2.setBorder(null);
        jPanel2.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 177, 36, 37));

        y3.setBackground(new java.awt.Color(199, 199, 199));
        y3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y3.setBorder(null);
        jPanel2.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 249, 36, 36));

        z1.setBackground(new java.awt.Color(199, 199, 199));
        z1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z1.setBorder(null);
        jPanel2.add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 110, 36, 36));

        z2.setBackground(new java.awt.Color(199, 199, 199));
        z2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z2.setBorder(null);
        jPanel2.add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 177, 36, 37));

        z3.setBackground(new java.awt.Color(199, 199, 199));
        z3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        z3.setBorder(null);
        jPanel2.add(z3, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 249, 36, 36));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("X");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Y");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Z");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        ti1.setEditable(false);
        ti1.setBackground(new java.awt.Color(199, 199, 199));
        ti1.setBorder(null);
        jPanel2.add(ti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 36, 36));

        ti2.setBackground(new java.awt.Color(199, 199, 199));
        ti2.setBorder(null);
        jPanel2.add(ti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 36, 36));

        ti3.setBackground(new java.awt.Color(199, 199, 199));
        ti3.setBorder(null);
        jPanel2.add(ti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 36, 36));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 200, 190));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("TI");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(30, 30, 30));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 20, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField ti1;
    private javax.swing.JTextField ti2;
    private javax.swing.JTextField ti3;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    private javax.swing.JTextField x3;
    private javax.swing.JTextField y1;
    private javax.swing.JTextField y2;
    private javax.swing.JTextField y3;
    private javax.swing.JTextField z1;
    private javax.swing.JTextField z2;
    private javax.swing.JTextField z3;
    // End of variables declaration//GEN-END:variables
}
